"""Add name and ingredients to RestaurantPizza model

Revision ID: 5e17cbfcb965
Revises: 54c1733139e1
Create Date: 2024-01-26 10:47:02.650596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e17cbfcb965'
down_revision = '54c1733139e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant_pizzas', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('name')
        batch_op.drop_column('ingredients')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant_pizzas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ingredients', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=255), nullable=True))
        batch_op.alter_column('price',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
